# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 856)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1090, 800))
        MainWindow.setStyleSheet("selection-color: rgb(85, 0, 127)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(820, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 240, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.stackedWidget.setPalette(palette)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("background-color: #D3F0EF; border-left:1px solid")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.line_6 = QtWidgets.QFrame(self.Home)
        self.line_6.setGeometry(QtCore.QRect(10, 67, 841, 3))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_40 = QtWidgets.QLabel(self.Home)
        self.label_40.setGeometry(QtCore.QRect(10, 10, 841, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("border: None;")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.Home)
        self.textBrowser_4.setGeometry(QtCore.QRect(40, 90, 791, 611))
        self.textBrowser_4.setStyleSheet("background-color: white")
        self.textBrowser_4.setSource(QtCore.QUrl("qrc:/HomePageText.html"))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.stackedWidget.addWidget(self.Home)
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.line_7 = QtWidgets.QFrame(self.History)
        self.line_7.setGeometry(QtCore.QRect(10, 67, 841, 3))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_41 = QtWidgets.QLabel(self.History)
        self.label_41.setGeometry(QtCore.QRect(10, 10, 841, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("border: None;")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.frame_4 = QtWidgets.QFrame(self.History)
        self.frame_4.setGeometry(QtCore.QRect(10, 80, 841, 211))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.History_Projo_comboBox = QtWidgets.QComboBox(self.frame_4)
        self.History_Projo_comboBox.setGeometry(QtCore.QRect(70, 20, 201, 25))
        self.History_Projo_comboBox.setStyleSheet("background-color: white;")
        self.History_Projo_comboBox.setMaxVisibleItems(11)
        self.History_Projo_comboBox.setObjectName("History_Projo_comboBox")
        self.QueryText = QtWidgets.QPlainTextEdit(self.History)
        self.QueryText.setGeometry(QtCore.QRect(10, 320, 841, 70))
        self.QueryText.setObjectName("QueryText")
        self.Query_Result = QtWidgets.QTableView(self.History)
        self.Query_Result.setGeometry(QtCore.QRect(30, 460, 801, 192))
        self.Query_Result.setObjectName("Query_Result")
        self.query_execute = QtWidgets.QPushButton(self.History)
        self.query_execute.setGeometry(QtCore.QRect(640, 420, 89, 25))
        self.query_execute.setObjectName("query_execute")
        self.stackedWidget.addWidget(self.History)
        self.Measure = QtWidgets.QWidget()
        self.Measure.setStyleSheet("background-color: #D3F0EF")
        self.Measure.setObjectName("Measure")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Measure)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Standby_label_5 = QtWidgets.QLabel(self.Measure)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Standby_label_5.setFont(font)
        self.Standby_label_5.setStyleSheet("color: green; border: none;BACKGROUND-COLOR: NONE;")
        self.Standby_label_5.setText("")
        self.Standby_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Standby_label_5.setObjectName("Standby_label_5")
        self.gridLayout_7.addWidget(self.Standby_label_5, 6, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 8, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.Measure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setStyleSheet("border: 1px solid;background-color: #A1EAF0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setStyleSheet("border: none; color: grey")
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setStyleSheet("border: None;")
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setStyleSheet("border: none; color: grey")
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border:None;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: None;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setStyleSheet("border: none;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 2, 0, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setStyleSheet("border: none; color: grey")
        self.label_17.setLineWidth(0)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setStyleSheet("border: none; color: red;")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setStyleSheet("border: none; color: red;")
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setStyleSheet("border: none; color: red;")
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setStyleSheet("border: none; color: red;")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setStyleSheet("border: none; color: grey")
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 6, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: None;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(20, 20))
        self.label_25.setMaximumSize(QtCore.QSize(20, 20))
        self.label_25.setStyleSheet("border: none;")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/images/images/Info_icon_001.svg"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame_2, 4, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.Measure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setStyleSheet("border: 1px solid;background-color: #A1EAF0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("border:None;")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: None;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 3)
        self.Measure_Grains_comboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Measure_Grains_comboBox.sizePolicy().hasHeightForWidth())
        self.Measure_Grains_comboBox.setSizePolicy(sizePolicy)
        self.Measure_Grains_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.Measure_Grains_comboBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.Measure_Grains_comboBox.setBaseSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Measure_Grains_comboBox.setFont(font)
        self.Measure_Grains_comboBox.setAutoFillBackground(False)
        self.Measure_Grains_comboBox.setStyleSheet("background-color: white;\n"
"selection-color: red;")
        self.Measure_Grains_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Measure_Grains_comboBox.setObjectName("Measure_Grains_comboBox")
        self.gridLayout_2.addWidget(self.Measure_Grains_comboBox, 2, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: None;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 2)
        self.Measure_Projo_comboBox = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Measure_Projo_comboBox.setFont(font)
        self.Measure_Projo_comboBox.setStyleSheet("background-color: white;\n"
"selection-color: red;")
        self.Measure_Projo_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Measure_Projo_comboBox.setObjectName("Measure_Projo_comboBox")
        self.gridLayout_2.addWidget(self.Measure_Projo_comboBox, 4, 1, 1, 2)
        self.Measure_Powder_comboBox = QtWidgets.QComboBox(self.frame)
        self.Measure_Powder_comboBox.setStyleSheet("background-color: white;\n"
"selection-color: red;")
        self.Measure_Powder_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Measure_Powder_comboBox.setObjectName("Measure_Powder_comboBox")
        self.gridLayout_2.addWidget(self.Measure_Powder_comboBox, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("border: None;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(20, 20))
        self.label_24.setMaximumSize(QtCore.QSize(20, 20))
        self.label_24.setStyleSheet("border: none;")
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/images/images/Info_icon_001.svg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 4, 3, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_7.addItem(spacerItem2, 9, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.Measure)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setStyleSheet("BORDER:NONE;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.FIRE_shot_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.FIRE_shot_pushButton.setGeometry(QtCore.QRect(0, 20, 101, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FIRE_shot_pushButton.sizePolicy().hasHeightForWidth())
        self.FIRE_shot_pushButton.setSizePolicy(sizePolicy)
        self.FIRE_shot_pushButton.setMinimumSize(QtCore.QSize(80, 100))
        self.FIRE_shot_pushButton.setBaseSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FIRE_shot_pushButton.setFont(font)
        self.FIRE_shot_pushButton.setStyleSheet("background-color: red;")
        self.FIRE_shot_pushButton.setObjectName("FIRE_shot_pushButton")
        self.gridLayout_7.addWidget(self.frame_3, 4, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.Measure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 1, 0, 3, 5)
        self.VelocityDataLabel = QtWidgets.QLabel(self.Measure)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.VelocityDataLabel.setFont(font)
        self.VelocityDataLabel.setStyleSheet("color: red; border: none;BACKGROUND-COLOR: NONE;")
        self.VelocityDataLabel.setText("")
        self.VelocityDataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VelocityDataLabel.setObjectName("VelocityDataLabel")
        self.gridLayout_7.addWidget(self.VelocityDataLabel, 7, 0, 1, 3)
        self.label_39 = QtWidgets.QLabel(self.Measure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("border: None;")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 0, 0, 1, 5)
        self.stackedWidget.addWidget(self.Measure)
        self.Settings = QtWidgets.QWidget()
        self.Settings.setStyleSheet("background-color: #D3F0EF")
        self.Settings.setObjectName("Settings")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Settings)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_3 = QtWidgets.QFrame(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 4)
        self.label_33 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("border: None;")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 0, 0, 1, 4)
        self.frame_10 = QtWidgets.QFrame(self.Settings)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_10.setMaximumSize(QtCore.QSize(200, 400))
        self.frame_10.setStyleSheet("border: 1px solid;background-color: #A1EAF0;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.Settings_AddPowder_lineEdit = QtWidgets.QLineEdit(self.frame_10)
        self.Settings_AddPowder_lineEdit.setStyleSheet("background-color: White;")
        self.Settings_AddPowder_lineEdit.setObjectName("Settings_AddPowder_lineEdit")
        self.gridLayout_12.addWidget(self.Settings_AddPowder_lineEdit, 3, 0, 1, 2)
        self.addPowders_PushButton = QtWidgets.QPushButton(self.frame_10)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.addPowders_PushButton.setPalette(palette)
        self.addPowders_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addPowders_PushButton.setAutoFillBackground(False)
        self.addPowders_PushButton.setStyleSheet("background-color: #A5F9AD ;")
        self.addPowders_PushButton.setObjectName("addPowders_PushButton")
        self.gridLayout_12.addWidget(self.addPowders_PushButton, 4, 1, 1, 1)
        self.rmvPowder_pushButton = QtWidgets.QPushButton(self.frame_10)
        self.rmvPowder_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rmvPowder_pushButton.setStyleSheet("background-color: #F9CEA5;")
        self.rmvPowder_pushButton.setObjectName("rmvPowder_pushButton")
        self.gridLayout_12.addWidget(self.rmvPowder_pushButton, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_10)
        self.label_20.setStyleSheet("border: None;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 2, 0, 1, 2)
        self.Powders_listView = QtWidgets.QListView(self.frame_10)
        self.Powders_listView.setStyleSheet("background-color: white;")
        self.Powders_listView.setObjectName("Powders_listView")
        self.gridLayout_12.addWidget(self.Powders_listView, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setStyleSheet("border: none;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame_10, 2, 2, 2, 1)
        self.frame_12 = QtWidgets.QFrame(self.Settings)
        self.frame_12.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_12.setStyleSheet("border: 1px solid;background-color: #A1EAF0;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_31 = QtWidgets.QLabel(self.frame_12)
        self.label_31.setStyleSheet("border: None;")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_13.addWidget(self.label_31, 2, 0, 1, 3)
        self.addProjectiles_pushButton = QtWidgets.QPushButton(self.frame_12)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.addProjectiles_pushButton.setPalette(palette)
        self.addProjectiles_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addProjectiles_pushButton.setAutoFillBackground(False)
        self.addProjectiles_pushButton.setStyleSheet("background-color: #A5F9AD ;")
        self.addProjectiles_pushButton.setObjectName("addProjectiles_pushButton")
        self.gridLayout_13.addWidget(self.addProjectiles_pushButton, 8, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_12)
        self.label_35.setStyleSheet("border: None;")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_13.addWidget(self.label_35, 6, 2, 1, 1)
        self.rmvProjectiles_pushButton = QtWidgets.QPushButton(self.frame_12)
        self.rmvProjectiles_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rmvProjectiles_pushButton.setStyleSheet("background-color: #F9CEA5;")
        self.rmvProjectiles_pushButton.setObjectName("rmvProjectiles_pushButton")
        self.gridLayout_13.addWidget(self.rmvProjectiles_pushButton, 8, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_12)
        self.label_34.setStyleSheet("border: None;")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_13.addWidget(self.label_34, 6, 1, 1, 1)
        self.Settings_AddProjectile_lineEdit = QtWidgets.QLineEdit(self.frame_12)
        self.Settings_AddProjectile_lineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.Settings_AddProjectile_lineEdit.setStyleSheet("background-color: White;")
        self.Settings_AddProjectile_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Settings_AddProjectile_lineEdit.setObjectName("Settings_AddProjectile_lineEdit")
        self.gridLayout_13.addWidget(self.Settings_AddProjectile_lineEdit, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_12)
        self.label_21.setStyleSheet("border: None;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 6, 0, 1, 1)
        self.DragCoef_lineEdit = QtWidgets.QLineEdit(self.frame_12)
        self.DragCoef_lineEdit.setStyleSheet("background-color: White;")
        self.DragCoef_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.DragCoef_lineEdit.setObjectName("DragCoef_lineEdit")
        self.gridLayout_13.addWidget(self.DragCoef_lineEdit, 7, 2, 1, 1)
        self.ProjoMass_lineEdit = QtWidgets.QLineEdit(self.frame_12)
        self.ProjoMass_lineEdit.setStyleSheet("background-color: White;")
        self.ProjoMass_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ProjoMass_lineEdit.setObjectName("ProjoMass_lineEdit")
        self.gridLayout_13.addWidget(self.ProjoMass_lineEdit, 7, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.frame_12)
        self.line_8.setMinimumSize(QtCore.QSize(300, 0))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_13.addWidget(self.line_8, 3, 0, 1, 3)
        self.label_32 = QtWidgets.QLabel(self.frame_12)
        self.label_32.setStyleSheet("border: None;")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_13.addWidget(self.label_32, 0, 0, 1, 3)
        self.Projectiles_tableView = QtWidgets.QTableView(self.frame_12)
        self.Projectiles_tableView.setStyleSheet("background-color: white;")
        self.Projectiles_tableView.setObjectName("Projectiles_tableView")
        self.gridLayout_13.addWidget(self.Projectiles_tableView, 1, 0, 1, 3)
        self.gridLayout_4.addWidget(self.frame_12, 2, 0, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(221, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 145, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 6, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.Settings)
        self.frame_11.setMinimumSize(QtCore.QSize(400, 40))
        self.frame_11.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_11.setStyleSheet("border: 1px solid;background-color: #A1EAF0;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(10, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 4, 1, 1, 1)
        self.label_muzmid_distunit = QtWidgets.QLabel(self.frame_11)
        self.label_muzmid_distunit.setStyleSheet("border: None;")
        self.label_muzmid_distunit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_muzmid_distunit.setObjectName("label_muzmid_distunit")
        self.gridLayout_3.addWidget(self.label_muzmid_distunit, 4, 2, 1, 1)
        self.label_s2targ_distunit = QtWidgets.QLabel(self.frame_11)
        self.label_s2targ_distunit.setStyleSheet("border: None;")
        self.label_s2targ_distunit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_s2targ_distunit.setObjectName("label_s2targ_distunit")
        self.gridLayout_3.addWidget(self.label_s2targ_distunit, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 3, 1, 1, 1)
        self.label_mids2_distunit = QtWidgets.QLabel(self.frame_11)
        self.label_mids2_distunit.setStyleSheet("border: None;")
        self.label_mids2_distunit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mids2_distunit.setObjectName("label_mids2_distunit")
        self.gridLayout_3.addWidget(self.label_mids2_distunit, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 2, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame_11)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 5, 0, 1, 4)
        self.lineEdit_MuzMid = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_MuzMid.setStyleSheet("background-color: white;")
        self.lineEdit_MuzMid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_MuzMid.setObjectName("lineEdit_MuzMid")
        self.gridLayout_3.addWidget(self.lineEdit_MuzMid, 4, 3, 1, 1)
        self.lineEdit_S1S2 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_S1S2.setStyleSheet("background-color: white;")
        self.lineEdit_S1S2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_S1S2.setObjectName("lineEdit_S1S2")
        self.gridLayout_3.addWidget(self.lineEdit_S1S2, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_11)
        self.label_26.setStyleSheet("border: None;")
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_11)
        self.label_27.setStyleSheet("border: None;")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)
        self.label_s1s2_distunit = QtWidgets.QLabel(self.frame_11)
        self.label_s1s2_distunit.setStyleSheet("border: None;")
        self.label_s1s2_distunit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_s1s2_distunit.setObjectName("label_s1s2_distunit")
        self.gridLayout_3.addWidget(self.label_s1s2_distunit, 1, 2, 1, 1)
        self.lineEdit_S2Targ = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_S2Targ.setStyleSheet("background-color: white;")
        self.lineEdit_S2Targ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_S2Targ.setObjectName("lineEdit_S2Targ")
        self.gridLayout_3.addWidget(self.lineEdit_S2Targ, 2, 3, 1, 1)
        self.lineEdit_MidS2 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_MidS2.setStyleSheet("background-color: white;")
        self.lineEdit_MidS2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_MidS2.setObjectName("lineEdit_MidS2")
        self.gridLayout_3.addWidget(self.lineEdit_MidS2, 3, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_11)
        self.label_28.setStyleSheet("border: None;")
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 4, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_11)
        self.label_29.setStyleSheet("border: None;")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_11)
        self.label_30.setStyleSheet("border: None;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 4)
        self.SaveRange_pushButton = QtWidgets.QPushButton(self.frame_11)
        self.SaveRange_pushButton.setStyleSheet("background-color: #A5F9AD ;")
        self.SaveRange_pushButton.setObjectName("SaveRange_pushButton")
        self.gridLayout_3.addWidget(self.SaveRange_pushButton, 6, 3, 1, 1)
        self.gridLayout_4.addWidget(self.frame_11, 4, 0, 1, 2)
        self.frame_9 = QtWidgets.QFrame(self.Settings)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_9.setMaximumSize(QtCore.QSize(200, 400))
        self.frame_9.setStyleSheet("border: 1px solid;background-color: #A1EAF0;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Settings_AddGrain_lineEdit = QtWidgets.QLineEdit(self.frame_9)
        self.Settings_AddGrain_lineEdit.setStyleSheet("background-color: White;")
        self.Settings_AddGrain_lineEdit.setObjectName("Settings_AddGrain_lineEdit")
        self.gridLayout_11.addWidget(self.Settings_AddGrain_lineEdit, 3, 0, 1, 2)
        self.addGrain_PushButton = QtWidgets.QPushButton(self.frame_9)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 249, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.addGrain_PushButton.setPalette(palette)
        self.addGrain_PushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addGrain_PushButton.setAutoFillBackground(False)
        self.addGrain_PushButton.setStyleSheet("background-color: #A5F9AD ;")
        self.addGrain_PushButton.setObjectName("addGrain_PushButton")
        self.gridLayout_11.addWidget(self.addGrain_PushButton, 4, 1, 1, 1)
        self.rmvGrains_pushButton = QtWidgets.QPushButton(self.frame_9)
        self.rmvGrains_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rmvGrains_pushButton.setStyleSheet("background-color: #F9CEA5;")
        self.rmvGrains_pushButton.setObjectName("rmvGrains_pushButton")
        self.gridLayout_11.addWidget(self.rmvGrains_pushButton, 4, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setStyleSheet("border: None;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 2, 0, 1, 2)
        self.Grains_listView = QtWidgets.QListView(self.frame_9)
        self.Grains_listView.setStyleSheet("background-color: white;")
        self.Grains_listView.setObjectName("Grains_listView")
        self.gridLayout_11.addWidget(self.Grains_listView, 1, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setStyleSheet("border: none;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame_9, 2, 1, 2, 1)
        self.Ranges_tableView = QtWidgets.QTableView(self.Settings)
        self.Ranges_tableView.setStyleSheet("background-color: white;")
        self.Ranges_tableView.setAlternatingRowColors(True)
        self.Ranges_tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Ranges_tableView.setObjectName("Ranges_tableView")
        self.gridLayout_4.addWidget(self.Ranges_tableView, 5, 0, 1, 3)
        self.stackedWidget.addWidget(self.Settings)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(200, 85))
        self.label_2.setStyleSheet("background-color:black;padding:10px;\n"
"margin: 3px")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/DuPont_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setStyleSheet("margin: 0 3")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/Gnome-go-home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(30, 30))
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_4.addWidget(self.homeButton)
        self.historyButton = QtWidgets.QPushButton(self.centralwidget)
        self.historyButton.setStyleSheet("margin: 0 3px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/Gnome-document-open-recent.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyButton.setIcon(icon1)
        self.historyButton.setIconSize(QtCore.QSize(30, 30))
        self.historyButton.setObjectName("historyButton")
        self.verticalLayout_4.addWidget(self.historyButton)
        self.measureButton = QtWidgets.QPushButton(self.centralwidget)
        self.measureButton.setStyleSheet("margin: 0 3px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/Circle-icons-circlecompass.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.measureButton.setIcon(icon2)
        self.measureButton.setIconSize(QtCore.QSize(30, 30))
        self.measureButton.setObjectName("measureButton")
        self.verticalLayout_4.addWidget(self.measureButton)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setStyleSheet("margin: 0 3px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/Circle-icons-settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon3)
        self.settingsButton.setIconSize(QtCore.QSize(30, 30))
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout_4.addWidget(self.settingsButton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quitButton.setStyleSheet("margin: 0 3 3 3px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/Circle-icons-power.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButton.setIcon(icon4)
        self.quitButton.setIconSize(QtCore.QSize(30, 30))
        self.quitButton.setObjectName("quitButton")
        self.verticalLayout_4.addWidget(self.quitButton)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Settings_AddProjectile_lineEdit, self.ProjoMass_lineEdit)
        MainWindow.setTabOrder(self.ProjoMass_lineEdit, self.DragCoef_lineEdit)
        MainWindow.setTabOrder(self.DragCoef_lineEdit, self.Settings_AddGrain_lineEdit)
        MainWindow.setTabOrder(self.Settings_AddGrain_lineEdit, self.Settings_AddPowder_lineEdit)
        MainWindow.setTabOrder(self.Settings_AddPowder_lineEdit, self.lineEdit_S1S2)
        MainWindow.setTabOrder(self.lineEdit_S1S2, self.lineEdit_S2Targ)
        MainWindow.setTabOrder(self.lineEdit_S2Targ, self.lineEdit_MidS2)
        MainWindow.setTabOrder(self.lineEdit_MidS2, self.lineEdit_MuzMid)
        MainWindow.setTabOrder(self.lineEdit_MuzMid, self.SaveRange_pushButton)
        MainWindow.setTabOrder(self.SaveRange_pushButton, self.measureButton)
        MainWindow.setTabOrder(self.measureButton, self.quitButton)
        MainWindow.setTabOrder(self.quitButton, self.addGrain_PushButton)
        MainWindow.setTabOrder(self.addGrain_PushButton, self.historyButton)
        MainWindow.setTabOrder(self.historyButton, self.Measure_Grains_comboBox)
        MainWindow.setTabOrder(self.Measure_Grains_comboBox, self.Measure_Projo_comboBox)
        MainWindow.setTabOrder(self.Measure_Projo_comboBox, self.settingsButton)
        MainWindow.setTabOrder(self.settingsButton, self.rmvProjectiles_pushButton)
        MainWindow.setTabOrder(self.rmvProjectiles_pushButton, self.textBrowser_4)
        MainWindow.setTabOrder(self.textBrowser_4, self.History_Projo_comboBox)
        MainWindow.setTabOrder(self.History_Projo_comboBox, self.QueryText)
        MainWindow.setTabOrder(self.QueryText, self.Query_Result)
        MainWindow.setTabOrder(self.Query_Result, self.query_execute)
        MainWindow.setTabOrder(self.query_execute, self.Measure_Powder_comboBox)
        MainWindow.setTabOrder(self.Measure_Powder_comboBox, self.FIRE_shot_pushButton)
        MainWindow.setTabOrder(self.FIRE_shot_pushButton, self.Grains_listView)
        MainWindow.setTabOrder(self.Grains_listView, self.addPowders_PushButton)
        MainWindow.setTabOrder(self.addPowders_PushButton, self.rmvPowder_pushButton)
        MainWindow.setTabOrder(self.rmvPowder_pushButton, self.Powders_listView)
        MainWindow.setTabOrder(self.Powders_listView, self.addProjectiles_pushButton)
        MainWindow.setTabOrder(self.addProjectiles_pushButton, self.rmvGrains_pushButton)
        MainWindow.setTabOrder(self.rmvGrains_pushButton, self.homeButton)
        MainWindow.setTabOrder(self.homeButton, self.Projectiles_tableView)
        MainWindow.setTabOrder(self.Projectiles_tableView, self.Ranges_tableView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dupont Ballistic Information Management System"))
        self.label_40.setText(_translate("MainWindow", "Home"))
        self.label_41.setText(_translate("MainWindow", "History"))
        self.query_execute.setText(_translate("MainWindow", "PushButton"))
        self.label_22.setText(_translate("MainWindow", "cm"))
        self.label_11.setText(_translate("MainWindow", "Screen2 to Target"))
        self.label_18.setText(_translate("MainWindow", "cm"))
        self.label_8.setText(_translate("MainWindow", "Screen1 to Screen 2"))
        self.label_9.setText(_translate("MainWindow", "Muzzle to Middle"))
        self.label_12.setText(_translate("MainWindow", "Middle to Screen 2"))
        self.label_17.setText(_translate("MainWindow", "cm"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "cm"))
        self.label_10.setText(_translate("MainWindow", "Range Distances"))
        self.label_25.setToolTip(_translate("MainWindow", "Change these values in Settings page"))
        self.label.setText(_translate("MainWindow", "Grains"))
        self.label_4.setText(_translate("MainWindow", "Projectile"))
        self.label_3.setText(_translate("MainWindow", "Threat Variables"))
        self.label_5.setText(_translate("MainWindow", "Powder"))
        self.label_24.setToolTip(_translate("MainWindow", "Set Threat Variables in Settings Page"))
        self.FIRE_shot_pushButton.setText(_translate("MainWindow", "  Fire shot  "))
        self.label_39.setText(_translate("MainWindow", "Measure"))
        self.label_33.setText(_translate("MainWindow", "Settings"))
        self.addPowders_PushButton.setText(_translate("MainWindow", "Add new"))
        self.rmvPowder_pushButton.setText(_translate("MainWindow", "Remove"))
        self.label_20.setText(_translate("MainWindow", "Add new powder below:"))
        self.label_7.setText(_translate("MainWindow", "Edit Powder list "))
        self.label_31.setText(_translate("MainWindow", "Add new projectile below:"))
        self.addProjectiles_pushButton.setText(_translate("MainWindow", "Add new"))
        self.label_35.setText(_translate("MainWindow", "Drag Coef"))
        self.rmvProjectiles_pushButton.setText(_translate("MainWindow", "Remove"))
        self.label_34.setText(_translate("MainWindow", "Mass"))
        self.label_21.setText(_translate("MainWindow", "Name or Type"))
        self.label_32.setText(_translate("MainWindow", "Edit Projectiles list"))
        self.label_muzmid_distunit.setText(_translate("MainWindow", "cm"))
        self.label_s2targ_distunit.setText(_translate("MainWindow", "cm"))
        self.label_mids2_distunit.setText(_translate("MainWindow", "cm"))
        self.label_26.setText(_translate("MainWindow", "Screen2 to Target"))
        self.label_27.setText(_translate("MainWindow", "Middle to Screen 2"))
        self.label_s1s2_distunit.setText(_translate("MainWindow", "cm"))
        self.label_28.setText(_translate("MainWindow", "Muzzle to Middle"))
        self.label_29.setText(_translate("MainWindow", "Screen1 to Screen 2"))
        self.label_30.setText(_translate("MainWindow", "Range Measurements"))
        self.SaveRange_pushButton.setText(_translate("MainWindow", "Save Range Values"))
        self.addGrain_PushButton.setText(_translate("MainWindow", "Add new"))
        self.rmvGrains_pushButton.setText(_translate("MainWindow", "Remove"))
        self.label_19.setText(_translate("MainWindow", "Add new grains below:"))
        self.label_6.setText(_translate("MainWindow", "Edit Grain Weights list "))
        self.homeButton.setText(_translate("MainWindow", "  Home"))
        self.historyButton.setText(_translate("MainWindow", "  History"))
        self.measureButton.setText(_translate("MainWindow", "  Measure"))
        self.settingsButton.setText(_translate("MainWindow", "  Settings"))
        self.quitButton.setText(_translate("MainWindow", "   Quit"))


